### ISSUE TITLE
Dedicated server console error on load A20.5 EXP

### ISSUE THREAD

**Issue by ktrainn** [OCB7D2D/OcbPrettyGrass#1]
Got this on load, windows dedicated server, new RWG world on A20.5EXP

2022-05-16T04:24:48 188.084 ERR [MODS] Error while executing GameStartDone on mod "PrettyGrass"
2022-05-16T04:24:48 188.089 EXC Object reference not set to an instance of an object

If anything else is needed, please advise.

**Comment by mgreter** [comment]
A complete log is always needed, otherwise this is not enough to investigate anything ...
Btw. this mod is not needed on the server (AFAIR), since it is only touching visual stuff which deds don't have.

**Comment by Shadow-Genesis** [comment]
I was about to give the same error message. I get it too. But I think its in the client side, single player, as well. My brain is a bit shot to say fully, but I am sure I seen it on the client side terminal as well.

If I see it again and remember, I will be sure to post it and the log.

**Comment by mgreter** [comment]
Please also make sure to mention the version you use, as I believe that version 0.1.2 might already fixed it.

**Comment by mgreter** [comment]
Closing as inactive, please re-open if you can provide more info!
